package apiPjt.soccerAPI;

import apiPjt.soccerAPI.domain.*;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;

import javax.persistence.EntityManager;
import java.time.LocalDate;

@Controller
@RequiredArgsConstructor
@Transactional
@Slf4j
public class MainController {
    private final EntityManager em;

    @GetMapping("/")
    public String index(){
        return "index";
    }

//    @RequestMapping("/")
//    public String start(){
//        log.info("ok");
//        Country korea=new Country("KOREA");
//        Country japan=new Country("JAPAN");
//        Country italia=new Country("ITALIA");
//        Country spain=new Country("SPAIN");
//        em.persist(korea);
//        em.persist(japan);
//        em.persist(italia);
//        em.persist(spain);
//
//        Club seoul=new Club("SEOUL");
//        Club tokyo=new Club("TOKYO");
//        Club daegu=new Club("DAEGU");
//        Club osaka=new Club("OSAKA");
//        Club barcelona=new Club("BARCELONA");
//        Club real_madrid=new Club("REAL_MADRID");
//        Club juventus=new Club("JUVENTUS");
//        Club psg=new Club("PSG");
//
//        Sponsor samsung=new Sponsor("SAMSUNG");
//        Sponsor apple=new Sponsor("APPLE");
//        Sponsor hyundai=new Sponsor("HYUNDAI");
//        Sponsor chanel=new Sponsor("CHANEL");
//        Sponsor toyota=new Sponsor("TOYOTA");
//        Sponsor wine=new Sponsor("WINE");
//        Sponsor intel=new Sponsor("INTEL");
//        Sponsor microsoft=new Sponsor("MICROSOFT");
//
//        seoul.sponsorSetting(samsung);
//        tokyo.sponsorSetting(toyota);
//        daegu.sponsorSetting(hyundai);
//        osaka.sponsorSetting(microsoft);
//        barcelona.sponsorSetting(chanel);
//        real_madrid.sponsorSetting(wine);
//        juventus.sponsorSetting(intel);
//        psg.sponsorSetting(apple);
//
//        em.persist(samsung);
//        em.persist(apple);
//        em.persist(hyundai);
//        em.persist(chanel);
//        em.persist(toyota);
//        em.persist(wine);
//        em.persist(intel);
//        em.persist(microsoft);
//
//        em.persist(seoul);
//        em.persist(tokyo);
//        em.persist(daegu);
//        em.persist(osaka);
//        em.persist(barcelona);
//        em.persist(real_madrid);
//        em.persist(juventus);
//        em.persist(psg);
//
//        Victory worldcup=new Victory(LocalDate.of(2022,8,15),"World Cup");
//        Victory championship=new Victory(LocalDate.of(2018,5,26),"UEFA Champions League");
//        em.persist(worldcup);
//        em.persist(championship);
//
//        Victorylist onlyworldcup1=new Victorylist();
//        Victorylist onlyworldcup2=new Victorylist();
//        Victorylist onlyworldcup3=new Victorylist();
//        Victorylist onlyworldcup4=new Victorylist();
//        Victorylist onlyworldcup5=new Victorylist();
//        Victorylist onlyworldcup6=new Victorylist();
//        Victorylist onlyworldcup7=new Victorylist();
//        Victorylist onlyworldcup8=new Victorylist();
//        Victorylist onlyworldcup9=new Victorylist();
//        Victorylist onlyworldcup10=new Victorylist();
//        Victorylist onlyworldcup11=new Victorylist();
//        Victorylist onlyworldcup12=new Victorylist();
//        Victorylist onlyworldcup13=new Victorylist();
//        Victorylist onlyworldcup14=new Victorylist();
//        Victorylist onlyworldcup15=new Victorylist();
//        Victorylist onlyworldcup16=new Victorylist();
//        Victorylist onlyworldcup17=new Victorylist();
//        Victorylist onlyworldcup18=new Victorylist();
//        Victorylist onlyworldcup19=new Victorylist();
//        Victorylist onlyworldcup20=new Victorylist();
//        Victorylist onlyworldcup21=new Victorylist();
//        Victorylist onlyworldcup22=new Victorylist();
//        Victorylist onlyworldcup23=new Victorylist();
//        Victorylist onlyworldcup24=new Victorylist();
//        onlyworldcup1.victorySetting(worldcup);
//        onlyworldcup2.victorySetting(worldcup);
//        onlyworldcup3.victorySetting(worldcup);
//        onlyworldcup4.victorySetting(worldcup);
//        onlyworldcup5.victorySetting(worldcup);
//        onlyworldcup6.victorySetting(worldcup);
//        onlyworldcup7.victorySetting(worldcup);
//        onlyworldcup8.victorySetting(worldcup);
//        onlyworldcup9.victorySetting(worldcup);
//        onlyworldcup10.victorySetting(worldcup);
//        onlyworldcup11.victorySetting(worldcup);
//        onlyworldcup12.victorySetting(worldcup);
//        onlyworldcup13.victorySetting(worldcup);
//        onlyworldcup14.victorySetting(worldcup);
//        onlyworldcup15.victorySetting(worldcup);
//        onlyworldcup16.victorySetting(worldcup);
//        onlyworldcup17.victorySetting(worldcup);
//        onlyworldcup18.victorySetting(worldcup);
//        onlyworldcup19.victorySetting(worldcup);
//        onlyworldcup20.victorySetting(worldcup);
//        onlyworldcup21.victorySetting(worldcup);
//        onlyworldcup22.victorySetting(worldcup);
//        onlyworldcup23.victorySetting(worldcup);
//        onlyworldcup24.victorySetting(worldcup);
//
//        Victorylist onlychamps1=new Victorylist();
//        Victorylist onlychamps2=new Victorylist();
//        Victorylist onlychamps3=new Victorylist();
//        Victorylist onlychamps4=new Victorylist();
//        Victorylist onlychamps5=new Victorylist();
//        Victorylist onlychamps6=new Victorylist();
//        Victorylist onlychamps7=new Victorylist();
//        Victorylist onlychamps8=new Victorylist();
//        onlychamps1.victorySetting(championship);
//        onlychamps2.victorySetting(championship);
//        onlychamps3.victorySetting(championship);
//        onlychamps4.victorySetting(championship);
//        onlychamps5.victorySetting(championship);
//        onlychamps6.victorySetting(championship);
//        onlychamps7.victorySetting(championship);
//        onlychamps8.victorySetting(championship);
//
//        em.persist(onlyworldcup1);
//        em.persist(onlyworldcup2);
//        em.persist(onlyworldcup3);
//        em.persist(onlyworldcup4);
//        em.persist(onlyworldcup5);
//        em.persist(onlyworldcup6);
//        em.persist(onlyworldcup7);
//        em.persist(onlyworldcup8);
//        em.persist(onlyworldcup9);
//        em.persist(onlyworldcup10);
//        em.persist(onlyworldcup11);
//        em.persist(onlyworldcup12);
//        em.persist(onlyworldcup13);
//        em.persist(onlyworldcup14);
//        em.persist(onlyworldcup15);
//        em.persist(onlyworldcup16);
//        em.persist(onlyworldcup17);
//        em.persist(onlyworldcup18);
//        em.persist(onlyworldcup19);
//        em.persist(onlyworldcup20);
//        em.persist(onlyworldcup21);
//        em.persist(onlyworldcup22);
//        em.persist(onlyworldcup23);
//        em.persist(onlyworldcup24);
//
//        em.persist(onlychamps1);
//        em.persist(onlychamps2);
//        em.persist(onlychamps3);
//        em.persist(onlychamps4);
//        em.persist(onlychamps5);
//        em.persist(onlychamps6);
//        em.persist(onlychamps7);
//        em.persist(onlychamps8);
//
//        Member member1=new Member("KIM SEUNG DAE",30,"FW");
//        Member member2=new Member("LEE JEONG HYEOP",30,"FW");
//        Member member3=new Member("KIM BO KYUNG",32,"MF");
//        Member member4=new Member("KIM IN SUNG",32,"MF");
//        Member member5=new Member("NA SANG HO",25,"MF");
//        Member member6=new Member("MOON SEONG MIN",29,"MF");
//        Member member7=new Member("SON JUN HO",29,"MF");
//        Member member8=new Member("YUN ILL OK",29,"MF");
//        Member member9=new Member("LEE YOUNG JAE",27,"MF");
//        Member member10=new Member("JU SE JONG",31,"MF");
//        Member member11=new Member("HAN SEUNG GYU",25,"MF");
//        Member member12=new Member("HAWNG IN BEOM",25,"MF");
//        Member member13=new Member("KWON KYUNG WON",29,"DF");
//        Member member14=new Member("KIM MOON HWAN",26,"DF");
//        Member member15=new Member("KIM MIN JAE",25,"DF");
//        Member member16=new Member("KIM YOUNG GWON",31,"DF");
//        Member member17=new Member("KIM JIN SU",29,"DF");
//        Member member18=new Member("KIM TAE HWAN",32,"DF");
//        Member member19=new Member("PARK JOO HO",34,"DF");
//        Member member20=new Member("PARK JI SU",27,"DF");
//        Member member21=new Member("GU SUNG YUN",27,"GK");
//        Member member22=new Member("KIM SEUNG GYU",31,"GK");
//        Member member23=new Member("JO HYEON WOO",30,"GK");
//        Member member24=new Member("SON HEUNG MIN",29,"MF");
//        member1.countrySetting(korea);
//        member2.countrySetting(korea);
//        member3.countrySetting(korea);
//        member4.countrySetting(korea);
//        member5.countrySetting(korea);
//        member6.countrySetting(korea);
//        member7.countrySetting(korea);
//        member8.countrySetting(korea);
//        member9.countrySetting(korea);
//        member10.countrySetting(korea);
//        member11.countrySetting(korea);
//        member12.countrySetting(korea);
//        member13.countrySetting(korea);
//        member14.countrySetting(korea);
//        member15.countrySetting(korea);
//        member16.countrySetting(korea);
//        member17.countrySetting(korea);
//        member18.countrySetting(korea);
//        member19.countrySetting(korea);
//        member20.countrySetting(korea);
//        member21.countrySetting(korea);
//        member22.countrySetting(korea);
//        member23.countrySetting(korea);
//        member24.countrySetting(korea);
//
//        member1.victorylistSetting(onlyworldcup1);
//        member2.victorylistSetting(onlyworldcup2);
//        member3.victorylistSetting(onlyworldcup3);
//        member4.victorylistSetting(onlyworldcup4);
//        member5.victorylistSetting(onlyworldcup5);
//        member6.victorylistSetting(onlyworldcup6);
//        member7.victorylistSetting(onlyworldcup7);
//        member8.victorylistSetting(onlyworldcup8);
//        member9.victorylistSetting(onlyworldcup9);
//        member10.victorylistSetting(onlyworldcup10);
//        member11.victorylistSetting(onlyworldcup11);
//        member12.victorylistSetting(onlyworldcup12);
//        member13.victorylistSetting(onlyworldcup13);
//        member14.victorylistSetting(onlyworldcup14);
//        member15.victorylistSetting(onlyworldcup15);
//        member16.victorylistSetting(onlyworldcup16);
//        member17.victorylistSetting(onlyworldcup17);
//        member18.victorylistSetting(onlyworldcup18);
//        member19.victorylistSetting(onlyworldcup19);
//        member20.victorylistSetting(onlyworldcup20);
//        member21.victorylistSetting(onlyworldcup21);
//        member22.victorylistSetting(onlyworldcup22);
//        member23.victorylistSetting(onlyworldcup23);
//        member24.victorylistSetting(onlyworldcup24);
//        member24.victorylistSetting(onlychamps1);
//
//        member1.clubSetting(seoul);
//        member2.clubSetting(daegu);
//        member3.clubSetting(seoul);
//        member4.clubSetting(psg);
//        member5.clubSetting(seoul);
//        member6.clubSetting(real_madrid);
//        member7.clubSetting(seoul);
//        member8.clubSetting(osaka);
//        member9.clubSetting(tokyo);
//        member10.clubSetting(seoul);
//        member11.clubSetting(seoul);
//        member12.clubSetting(seoul);
//        member13.clubSetting(seoul);
//        member14.clubSetting(seoul);
//        member15.clubSetting(seoul);
//        member16.clubSetting(seoul);
//        member17.clubSetting(daegu);
//        member18.clubSetting(daegu);
//        member19.clubSetting(daegu);
//        member20.clubSetting(daegu);
//        member21.clubSetting(daegu);
//        member22.clubSetting(daegu);
//        member23.clubSetting(daegu);
//        member24.clubSetting(barcelona);
//
//        em.persist(member1);
//        em.persist(member2);
//        em.persist(member3);
//        em.persist(member4);
//        em.persist(member5);
//        em.persist(member6);
//        em.persist(member7);
//        em.persist(member8);
//        em.persist(member9);
//        em.persist(member10);
//        em.persist(member11);
//        em.persist(member12);
//        em.persist(member13);
//        em.persist(member14);
//        em.persist(member15);
//        em.persist(member16);
//        em.persist(member17);
//        em.persist(member18);
//        em.persist(member19);
//        em.persist(member20);
//        em.persist(member21);
//        em.persist(member22);
//        em.persist(member23);
//        em.persist(member24);
//
//        Member smember1=new Member("DE GEA",31,"GK");
//        Member smember2=new Member("CARVAJAL",29,"DF");
//        Member smember3=new Member("PIQUE",34,"DF");
//        Member smember4=new Member("BUSQUETS",33,"MF");
//        Member smember5=new Member("INIESTA",37,"MF");
//        Member smember6=new Member("THIAGO",29,"MF");
//        Member smember7=new Member("DIEGO",33,"FW");
//        Member smember8=new Member("ASPAS",34,"FW");
//        Member smember9=new Member("VAZQUEZ",30,"FW");
//        Member smember10=new Member("REINA",39,"GK");
//        Member smember11=new Member("SILVA",35,"MF");
//        smember1.countrySetting(spain);
//        smember2.countrySetting(spain);
//        smember3.countrySetting(spain);
//        smember4.countrySetting(spain);
//        smember5.countrySetting(spain);
//        smember6.countrySetting(spain);
//        smember7.countrySetting(spain);
//        smember8.countrySetting(spain);
//        smember9.countrySetting(spain);
//        smember10.countrySetting(spain);
//        smember11.countrySetting(spain);
//        smember1.clubSetting(barcelona);
//        smember2.clubSetting(barcelona);
//        smember3.clubSetting(barcelona);
//        smember4.clubSetting(barcelona);
//        smember5.clubSetting(barcelona);
//        smember6.clubSetting(barcelona);
//        smember7.clubSetting(barcelona);
//        smember8.clubSetting(juventus);
//        smember9.clubSetting(juventus);
//        smember10.clubSetting(juventus);
//        smember11.clubSetting(juventus);
//        smember1.victorylistSetting(onlychamps2);
//        smember2.victorylistSetting(onlychamps3);
//        smember3.victorylistSetting(onlychamps4);
//        smember4.victorylistSetting(onlychamps5);
//        smember5.victorylistSetting(onlychamps6);
//        smember6.victorylistSetting(onlychamps7);
//        smember7.victorylistSetting(onlychamps8);
//
//        em.persist(smember1);
//        em.persist(smember2);
//        em.persist(smember3);
//        em.persist(smember4);
//        em.persist(smember5);
//        em.persist(smember6);
//        em.persist(smember7);
//        em.persist(smember8);
//        em.persist(smember9);
//        em.persist(smember10);
//        em.persist(smember11);
//
//
//        Member jmember1=new Member("KAGAWA",32,"MF");
//        Member jmember2=new Member("NAGATOMO",34,"MF");
//        Member jmember3=new Member("GEN",28,"DF");
//        Member jmember4=new Member("GAKU",30,"MF");
//        Member jmember5=new Member("RITZ",33,"GK");
//        Member jmember6=new Member("SHOYA",26,"FW");
//        Member jmember7=new Member("SHINJI",31,"FW");
//        Member jmember8=new Member("UYA",30,"DF");
//        Member jmember9=new Member("TAKEHIRO",36,"MF");
//        Member jmember10=new Member("KENYU",35,"MF");
//        Member jmember11=new Member("DAKASHI",33,"DF");
//        jmember1.countrySetting(japan);
//        jmember2.countrySetting(japan);
//        jmember3.countrySetting(japan);
//        jmember4.countrySetting(japan);
//        jmember5.countrySetting(japan);
//        jmember6.countrySetting(japan);
//        jmember7.countrySetting(japan);
//        jmember8.countrySetting(japan);
//        jmember9.countrySetting(japan);
//        jmember10.countrySetting(japan);
//        jmember11.countrySetting(japan);
//        jmember1.clubSetting(tokyo);
//        jmember2.clubSetting(tokyo);
//        jmember3.clubSetting(tokyo);
//        jmember4.clubSetting(tokyo);
//        jmember5.clubSetting(tokyo);
//        jmember6.clubSetting(osaka);
//        jmember7.clubSetting(osaka);
//        jmember8.clubSetting(osaka);
//        jmember9.clubSetting(osaka);
//        jmember10.clubSetting(psg);
//        jmember11.clubSetting(psg);
//
//        em.persist(jmember1);
//        em.persist(jmember2);
//        em.persist(jmember3);
//        em.persist(jmember4);
//        em.persist(jmember5);
//        em.persist(jmember6);
//        em.persist(jmember7);
//        em.persist(jmember8);
//        em.persist(jmember9);
//        em.persist(jmember10);
//        em.persist(jmember11);
//
//        Member imember1=new Member("BUFFON",28,"GK");
//        Member imember2=new Member("ZACARDO",24,"DF");
//        Member imember3=new Member("GROSO",28,"DF");
//        Member imember4=new Member("DE ROSHI",22,"DF");
//        Member imember5=new Member("DELPIERO",31,"FW");
//        Member imember6=new Member("TOTTI",29,"MF");
//        Member imember7=new Member("NESTA",30,"DF");
//        Member imember8=new Member("INZAGHI",32,"FW");
//        Member imember9=new Member("FEROTA",28,"MF");
//        Member imember10=new Member("BARONE",28,"MF");
//        Member imember11=new Member("ALBERTO",23,"FW");
//        imember1.countrySetting(italia);
//        imember2.countrySetting(italia);
//        imember3.countrySetting(italia);
//        imember4.countrySetting(italia);
//        imember5.countrySetting(italia);
//        imember6.countrySetting(italia);
//        imember7.countrySetting(italia);
//        imember8.countrySetting(italia);
//        imember9.countrySetting(italia);
//        imember10.countrySetting(italia);
//        imember11.countrySetting(italia);
//        imember1.clubSetting(psg);
//        imember2.clubSetting(psg);
//        imember3.clubSetting(psg);
//        imember4.clubSetting(psg);
//        imember5.clubSetting(real_madrid);
//        imember6.clubSetting(real_madrid);
//        imember7.clubSetting(real_madrid);
//        imember8.clubSetting(real_madrid);
//        imember9.clubSetting(juventus);
//        imember10.clubSetting(juventus);
//        imember11.clubSetting(juventus);
//        em.persist(imember1);
//        em.persist(imember2);
//        em.persist(imember3);
//        em.persist(imember4);
//        em.persist(imember5);
//        em.persist(imember6);
//        em.persist(imember7);
//        em.persist(imember8);
//        em.persist(imember9);
//        em.persist(imember10);
//        em.persist(imember11);
//
//
//        return "index";
//    }

}
